function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Mar-2018 18:49:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',1.25);
set(plot1(1),'Marker','o','DisplayName','n = 3');
set(plot1(2),'Marker','+','DisplayName','n = 4');
set(plot1(3),'Marker','*','DisplayName','n = 5');
set(plot1(4),'Marker','square','DisplayName','n = 6');
set(plot1(5),'Marker','x','DisplayName','n = 7');
set(plot1(6),'Marker','diamond','DisplayName','n = 8');

% Create xlabel
xlabel('Feed Water Temperature [°C]');

% Create ylabel
ylabel('Feed Water Flow Rate [kg/s]');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Orientation','horizontal','Location','NorthOutside');

